# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewuser',
            old_name='user',
            new_name='user_review',
        ),
        migrations.AddField(
            model_name='reviewuser',
            name='user_is_reviewed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
