# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ejobs', '0003_auto_20180205_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='comment date'),
        ),
        migrations.AddField(
            model_name='reply',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='reply date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='post date'),
        ),
    ]
