# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejobs', '0004_auto_20180205_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ejobs.Service'),
            preserve_default=False,
        ),
    ]
