# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejobs', '0008_remove_service_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.CharField(max_length=100),
        ),
    ]
