# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejobs', '0006_auto_20180210_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
