# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejobs', '0007_service_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
    ]
